/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<
      'home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'not-found': RouteRecordInfo<
      'not-found',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'self': RouteRecordInfo<
      'self',
      '/record-self',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'record-stories': RouteRecordInfo<
      'record-stories',
      '/record-stories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'roll': RouteRecordInfo<
      'roll',
      '/roll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'timer': RouteRecordInfo<
      'timer',
      '/timer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'coc-card': RouteRecordInfo<
      'coc-card',
      '/coc-card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'erp-card': RouteRecordInfo<
      'erp-card',
      '/erp-card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'infinity-skill-table': RouteRecordInfo<
      'infinity-skill-table',
      '/infinity-skill-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'kp-ads': RouteRecordInfo<
      'kp-ads',
      '/kp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'scenario-editor': RouteRecordInfo<
      'scenario-editor',
      '/scenario-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'scenario-module': RouteRecordInfo<
      'scenario-module',
      '/scenario-editor/module/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    'voyage': RouteRecordInfo<
      'voyage',
      '/voyage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(home)/index.vue': {
      routes:
        | 'home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(home)/[...path].vue': {
      routes:
        | 'not-found'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/(record)/record-self.vue': {
      routes:
        | 'self'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(record)/record-stories.vue': {
      routes:
        | 'record-stories'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(tools)/roll.vue': {
      routes:
        | 'roll'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(tools)/timer.vue': {
      routes:
        | 'timer'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/coc-card.vue': {
      routes:
        | 'coc-card'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/erp-card.vue': {
      routes:
        | 'erp-card'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/infinity-skill-table.vue': {
      routes:
        | 'infinity-skill-table'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/kp.vue': {
      routes:
        | 'kp-ads'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/scenario-editor/index.vue': {
      routes:
        | 'scenario-editor'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/scenario-editor/module/[name].vue': {
      routes:
        | 'scenario-module'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'src/pages/voyage.vue': {
      routes:
        | 'voyage'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
