import type { Weapon, WeaponGroups } from '@/types/coc-card/weapon';

type WeaponWithInfo = Weapon & {
  price: string;
  time: string;
};

export const weapons: WeaponWithInfo[] = [
  {
    name: '徒手格斗',
    skill: '格斗(斗殴)',
    dam: '1D3+DB',
    tho: 0,
    range: '近',
    round: '1',
    num: '1',
    price: '0',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '弓箭',
    skill: '射击(弓弩)',
    dam: '1D6+半DB',
    tho: 0,
    range: '30m',
    round: '1',
    num: '1',
    price: '7/75',
    err: '97',
    time: '1920s，现代',
  },
  {
    name: '黄铜指虎',
    skill: '格斗(斗殴)',
    dam: '1D3+1+DB',
    tho: 0,
    range: '近',
    round: '1',
    num: '1',
    price: '1/10',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '长鞭',
    skill: '格斗(鞭)',
    dam: '1D3+半DB',
    tho: 0,
    range: '3m',
    round: '1',
    num: '1',
    price: '5/50',
    err: '97',
    time: '1920s',
  },
  {
    name: '燃烧的火把',
    skill: '格斗(斗殴)',
    dam: '1D6+燃烧',
    tho: 0,
    range: '近',
    round: '1',
    num: '',
    price: '0.05/0.5',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '链锯',
    skill: '格斗(链锯)',
    dam: '2D8',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '-/300',
    err: '95',
    time: '现代',
  },
  {
    name: '包革金属棒(大头棍、护身棒)',
    skill: '格斗(斗殴)',
    dam: '1D8+DB',
    tho: 0,
    range: '近',
    round: '1',
    num: '',
    price: '2/15',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '大棒(棒球棒、拨火棍)',
    skill: '格斗(斗殴)',
    dam: '1D8+DB',
    tho: 0,
    range: '近',
    round: '1',
    num: '',
    price: '3/35',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '小型棍棒(警棍)',
    skill: '格斗(斗殴)',
    dam: '1D6+DB',
    tho: 0,
    range: '近',
    round: '1',
    num: '',
    price: '3/35',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '弩',
    skill: '射击(弓弩)',
    dam: '1D8+2',
    tho: 1,
    range: '46m',
    round: '1/2',
    num: '1',
    price: '10/100',
    err: '96',
    time: '1920s，现代',
  },
  {
    name: '绞索',
    skill: '格斗(绞索)',
    dam: '1D6+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '0.5/3',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '手斧/手镰',
    skill: '格斗(斧)',
    dam: '1D6+1+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '3/9',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '大型刀(甘蔗刀等)',
    skill: '格斗(斗殴)',
    dam: '1D8+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '4/50',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '中型刀(切肉餐刀等)',
    skill: '格斗(斗殴)',
    dam: '1D4+2+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '2/15',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '小型刀(弹簧折叠刀等)',
    skill: '格斗(斗殴)',
    dam: '1D4+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '2/6',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '220V通电导线',
    skill: '格斗(斗殴)',
    dam: '2D8+晕',
    tho: 0,
    range: '近',
    round: '1',
    num: '',
    price: '',
    err: '95',
    time: '现代',
  },
  {
    name: '催泪瓦斯',
    skill: '格斗(斗殴)',
    dam: '晕',
    tho: 0,
    range: '1.8m',
    round: '1',
    num: '25',
    price: '-/10',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '双节棍',
    skill: '格斗(链枷)',
    dam: '1D8+DB',
    tho: 0,
    range: '近',
    round: '1',
    num: '',
    price: '1/10',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '投石',
    skill: '投掷',
    dam: '1D4+半DB',
    tho: 0,
    range: 'STRft',
    round: '1',
    num: '',
    price: '',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '手里剑',
    skill: '投掷',
    dam: '1D3+半DB',
    tho: 1,
    range: '18m',
    round: '2',
    num: '1',
    price: '0.5/3',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '矛、骑士长枪',
    skill: '格斗(矛)',
    dam: '1D8+1',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '25/150',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '投矛',
    skill: '投掷',
    dam: '1D8+半DB',
    tho: 1,
    range: 'STRft',
    round: '1',
    num: '',
    price: '42760',
    err: '',
    time: '稀有',
  },
  {
    name: '大型剑(马刀)',
    skill: '格斗(刀剑)',
    dam: '1D8+1+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '30/75',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '中型剑(佩剑、重剑)',
    skill: '格斗(刀剑)',
    dam: '1D6+1+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '15/100',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '轻型剑(花剑、剑杖)',
    skill: '格斗(刀剑)',
    dam: '1D6+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '25/100',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '电击枪(接触)',
    skill: '格斗(斗殴)',
    dam: '1D3+晕',
    tho: 0,
    range: '近',
    round: '1',
    num: '',
    price: '-/200',
    err: '97',
    time: '现代',
  },
  {
    name: '电击枪(射击)',
    skill: '射击(手枪)',
    dam: '1D3+晕',
    tho: 0,
    range: '15ft',
    round: '1',
    num: '3',
    price: '-/400',
    err: '95',
    time: '现代',
  },
  {
    name: '战斗回力镖',
    skill: '投掷',
    dam: '1D8+半DB',
    tho: 0,
    range: '20',
    round: '1',
    num: '',
    price: '2/4',
    err: '',
    time: '稀有',
  },
  {
    name: '伐木斧',
    skill: '格斗(斧)',
    dam: '1D8+2+DB',
    tho: 1,
    range: '近',
    round: '1',
    num: '',
    price: '5/10',
    err: '',
    time: '1920s，现代',
  },
  {
    name: '燧发手枪',
    skill: '射击(手枪)',
    dam: '1D6+1',
    tho: 1,
    range: '10m',
    round: '1/4',
    num: '1',
    price: '30/300',
    err: '95',
    time: '稀有',
  },
  {
    name: '.22(5.6mm)小型自动手枪',
    skill: '射击(手枪)',
    dam: '1D6',
    tho: 1,
    range: '10',
    round: '1(3)',
    num: '6',
    price: '25/190',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '.25(6.35mm)短口手枪(单管)',
    skill: '射击(手枪)',
    dam: '1D6',
    tho: 1,
    range: '3',
    round: '1',
    num: '1',
    price: '12/55',
    err: '100',
    time: '1920s',
  },
  {
    name: '.32(7.65mm)左轮',
    skill: '射击(手枪)',
    dam: '1D8',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '6',
    price: '15/200',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '.32(7.65mm)自动手枪',
    skill: '射击(手枪)',
    dam: '1D8',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '8',
    price: '20/350',
    err: '99',
    time: '1920s，现代',
  },
  {
    name: '.357马格南左轮',
    skill: '射击(手枪)',
    dam: '1D8+1D4',
    tho: 1,
    range: '.357马格南左轮',
    round: '1(3)',
    num: '6',
    price: '425',
    err: '100',
    time: '现代',
  },
  {
    name: '.38(9mm)左轮',
    skill: '射击(手枪)',
    dam: '1D10',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '6',
    price: '25/200',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '.38(9mm)自动手枪',
    skill: '射击(手枪)',
    dam: '1D10',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '8',
    price: '30/375',
    err: '99',
    time: '1920s，现代',
  },
  {
    name: '贝瑞塔M9',
    skill: '射击(手枪)',
    dam: '1D10',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '15',
    price: '-/500',
    err: '98',
    time: '现代',
  },
  {
    name: '9mm格洛克17',
    skill: '射击(手枪)',
    dam: '1D10',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '17',
    price: '-/500',
    err: '98',
    time: '现代',
  },
  {
    name: '9mm鲁格P08',
    skill: '射击(手枪)',
    dam: '1D10',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '8',
    price: '75/600',
    err: '99',
    time: '1920s，现代',
  },
  {
    name: '.41(10.4mm)左轮',
    skill: '射击(手枪)',
    dam: '1D10',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '8',
    price: '30/-',
    err: '100',
    time: '1920s稀有',
  },
  {
    name: '.44(11.2mm)马格南左轮',
    skill: '射击(手枪)',
    dam: '1D10+1D4+2',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '6',
    price: '-/475',
    err: '100',
    time: '现代',
  },
  {
    name: '.45(11.43mm)左轮',
    skill: '射击(手枪)',
    dam: '1D10+2',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '6',
    price: '30/300',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '.45(11.43mm)自动手枪',
    skill: '射击(手枪)',
    dam: '1D10+2',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '7',
    price: '40/375',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: 'IMI 沙漠之鹰',
    skill: '射击(手枪)',
    dam: '1D10+1D6+3',
    tho: 1,
    range: '15',
    round: '1(3)',
    num: '7',
    price: '-/650',
    err: '94',
    time: '现代',
  },
  {
    name: '.58 (14.7mm)1855年式春田步枪',
    skill: '射击(步/霰)',
    dam: '1D10+4',
    tho: 1,
    range: '60',
    round: '1/4',
    num: '1',
    price: '25/350',
    err: '95',
    time: '稀有',
  },
  {
    name: '.22 (5.6mm)栓式枪机步枪',
    skill: '射击(步/霰)',
    dam: '1D6+1',
    tho: 1,
    range: '30',
    round: '1',
    num: '6',
    price: '13/70',
    err: '99',
    time: '1920s，现代',
  },
  {
    name: '.30 (7.62mm)杠杆式枪机步枪',
    skill: '射击(步/霰)',
    dam: '2D6',
    tho: 1,
    range: '50',
    round: '1',
    num: '6',
    price: '19/150',
    err: '98',
    time: '1920s，现代',
  },
  {
    name: '.45 (11.43mm)马蒂尼-亨利步枪',
    skill: '射击(步/霰)',
    dam: '1D8+1D6+3',
    tho: 1,
    range: '80',
    round: '1/3',
    num: '1',
    price: '20/200',
    err: '100',
    time: '1920s',
  },
  {
    name: '莫兰上校的气动步枪③',
    skill: '射击(步/霰)',
    dam: '2D6+1',
    tho: 1,
    range: '20',
    round: '1/3',
    num: '1',
    price: '200/-',
    err: '88',
    time: '1920s',
  },
  {
    name: '加兰德M1、M2步枪',
    skill: '射击(步/霰)',
    dam: '2D6+4',
    tho: 1,
    range: '110',
    round: '1',
    num: '8',
    price: '-/400',
    err: '100',
    time: '二战及以后',
  },
  {
    name: 'SKS半自动步枪(56半)',
    skill: '射击(步/霰)',
    dam: '2D6+1',
    tho: 1,
    range: '90',
    round: '1(2)',
    num: '10',
    price: '-/500',
    err: '97',
    time: '现代',
  },
  {
    name: '.303(7.7mm)李-恩菲尔德',
    skill: '射击(步/霰)',
    dam: '2D6+4',
    tho: 1,
    range: '110',
    round: '1',
    num: '5',
    price: '50/300',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '.30-06(7.62mm)手动枪机步枪',
    skill: '射击(步/霰)',
    dam: '2D6+4',
    tho: 1,
    range: '110',
    round: '1',
    num: '5',
    price: '75/175',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '.30-06(7.62mm)半自动步枪',
    skill: '射击(步/霰)',
    dam: '2D6+4',
    tho: 1,
    range: '110',
    round: '1',
    num: '5',
    price: '-/275',
    err: '100',
    time: '现代',
  },
  {
    name: '.444(11.28mm)马林步枪',
    skill: '射击(步/霰)',
    dam: '2D8+4',
    tho: 1,
    range: '110',
    round: '1',
    num: '5',
    price: '-/400',
    err: '98',
    time: '现代',
  },
  {
    name: '猎象枪(双管)',
    skill: '射击(步/霰)',
    dam: '3D6+4',
    tho: 1,
    range: '100',
    round: '1或2',
    num: '2',
    price: '400/1000',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: 'AK-47或AKM',
    skill: '射击(步/霰)',
    dam: '2D6+1',
    tho: 1,
    range: '100',
    round: '1(2)或全自动',
    num: '30',
    price: '200',
    err: '100',
    time: '现代',
  },
  {
    name: 'AK-74',
    skill: '射击(步/霰)',
    dam: '2D6+1',
    tho: 1,
    range: '110',
    round: '1(2)或全自动',
    num: '30',
    price: '1000',
    err: '97',
    time: '现代',
  },
  {
    name: 'M1918式勃朗宁自动步枪',
    skill: '射击(机枪)',
    dam: '2D6+4',
    tho: 1,
    range: '90',
    round: '1(2)或全自动',
    num: '20',
    price: '800/1500',
    err: '100',
    time: '1920s',
  },
  {
    name: 'FN FAL 突击步枪',
    skill: '射击(步/霰)',
    dam: '2D6+4',
    tho: 1,
    range: '110',
    round: '1-3发点射',
    num: '20',
    price: '1500',
    err: '97',
    time: '现代',
  },
  {
    name: '加利尔突击步枪',
    skill: '射击(步/霰)',
    dam: '2D6',
    tho: 1,
    range: '110',
    round: '1(2)或全自动',
    num: '20',
    price: '2000',
    err: '98',
    time: '现代',
  },
  {
    name: 'M16A2',
    skill: '射击(步/霰)',
    dam: '2D6',
    tho: 1,
    range: '110',
    round: '1-3发点射',
    num: '30',
    price: '',
    err: '97',
    time: '现代',
  },
  {
    name: 'M4',
    skill: '射击(步/霰)',
    dam: '2D6',
    tho: 1,
    range: '90',
    round: '1或3发点射',
    num: '30',
    price: '',
    err: '97',
    time: '现代',
  },
  {
    name: '斯泰尔AUG',
    skill: '射击(步/霰)',
    dam: '2D6',
    tho: 1,
    range: '110',
    round: '1(2)或全自动',
    num: '30',
    price: '1100',
    err: '99',
    time: '现代',
  },
  {
    name: '贝雷塔AR70/90',
    skill: '射击(步/霰)',
    dam: '2D6',
    tho: 1,
    range: '110',
    round: '1或全自动',
    num: '30',
    price: '2800',
    err: '99',
    time: '现代',
  },
  {
    name: '20号霰弹枪(双管)',
    skill: '射击(步/霰)',
    dam: '2D6/1D6/1D3',
    tho: 0,
    range: '10/20/50',
    round: '1或2',
    num: '2',
    price: '35/稀',
    err: '100',
    time: '1920s',
  },
  {
    name: '16号霰弹枪(双管)',
    skill: '射击(步/霰)',
    dam: '2D6+2/1D6+1/1D4',
    tho: 0,
    range: '10/20/50',
    round: '1或2',
    num: '2',
    price: '40/稀',
    err: '100',
    time: '1920s',
  },
  {
    name: '12号霰弹枪(双管)',
    skill: '射击(步/霰)',
    dam: '4D6/2D6/1D6',
    tho: 0,
    range: '10/20/50',
    round: '1或2',
    num: '2',
    price: '40/200',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '12号霰弹枪(手压式)',
    skill: '射击(步/霰)',
    dam: '4D6/2D6/1D6',
    tho: 0,
    range: '10/20/50',
    round: '1',
    num: '5',
    price: '45/100',
    err: '100',
    time: '现代',
  },
  {
    name: '12号霰弹枪(半自动)',
    skill: '射击(步/霰)',
    dam: '4D6/2D6/1D6',
    tho: 0,
    range: '10/20/50',
    round: '1(2)',
    num: '5',
    price: '45/100',
    err: '100',
    time: '现代',
  },
  {
    name: '12号霰弹枪(双管,锯短)',
    skill: '射击(步/霰)',
    dam: '4D6/1D6',
    tho: 0,
    range: '5/10',
    round: '1或2',
    num: '2',
    price: '',
    err: '100',
    time: '1920s',
  },
  {
    name: '10号霰弹枪(双管)',
    skill: '射击(步/霰)',
    dam: '4D6+2/2D6+1/1D4',
    tho: 0,
    range: '10/20/50',
    round: '1或2',
    num: '2',
    price: '稀',
    err: '100',
    time: '1920s稀有',
  },
  {
    name: '12号贝里尼M3(折叠式枪托)',
    skill: '射击(步/霰)',
    dam: '4D6/2D6/1D6',
    tho: 0,
    range: '10/20/50',
    round: '1(2)',
    num: '7',
    price: '-/895',
    err: '100',
    time: '现代',
  },
  {
    name: '12号SPAS (折叠式枪托)',
    skill: '射击(步/霰)',
    dam: '4D6/2D6/1D6',
    tho: 0,
    range: '10/20/50',
    round: '1',
    num: '8',
    price: '-/600',
    err: '98',
    time: '现代',
  },
  {
    name: 'MP18I/M现代28II',
    skill: '射击(冲锋枪)',
    dam: '1D10',
    tho: 1,
    range: '20',
    round: '1(2)或全自动',
    num: '20/30/32',
    price: '1000/20000',
    err: '96',
    time: '1920s',
  },
  {
    name: 'MP5',
    skill: '射击(冲锋枪)',
    dam: '1D10',
    tho: 1,
    range: '20',
    round: '1(2)或全自动',
    num: '15/30',
    price: '',
    err: '97',
    time: '现代',
  },
  {
    name: 'MAC-11',
    skill: '射击(冲锋枪)',
    dam: '1D10',
    tho: 1,
    range: '15',
    round: '1(3)或全自动',
    num: '32',
    price: '-/750',
    err: '96',
    time: '现代',
  },
  {
    name: '蝎式',
    skill: '射击(冲锋枪)',
    dam: '1D8',
    tho: 1,
    range: '15',
    round: '1(3)或全自动',
    num: '20',
    price: '',
    err: '96',
    time: '现代',
  },
  {
    name: '汤普森',
    skill: '射击(冲锋枪)',
    dam: '1D10+2',
    tho: 1,
    range: '20',
    round: '1或全自动',
    num: '20/30/50',
    price: '200+/1600',
    err: '96',
    time: '1920s',
  },
  {
    name: '乌兹',
    skill: '射击(冲锋枪)',
    dam: '1D10',
    tho: 1,
    range: '20',
    round: '1(2)或全自动',
    num: '32',
    price: '-/1000',
    err: '98',
    time: '现代',
  },
  {
    name: '巴雷特M82',
    skill: '射击(步/霰)',
    dam: '2D10+1D8+6',
    tho: 1,
    range: '250',
    round: '1',
    num: '11',
    price: '3000',
    err: '96',
    time: '现代',
  },
  {
    name: 'PTRD-41反坦克步枪',
    skill: '射击(步/霰)',
    dam: '2D10+1D10+8',
    tho: 1,
    range: '230',
    round: '1',
    num: '5',
    price: '1500',
    err: '94',
    time: '现代',
  },
  {
    name: '1882年式加特林',
    skill: '射击(机枪)',
    dam: '2D6+4',
    tho: 1,
    range: '100',
    round: '全自动',
    num: '200',
    price: '2000/14000',
    err: '96',
    time: '1920s稀有',
  },
  {
    name: '勃朗宁M1917A1(7.62mm)',
    skill: '射击(机枪)',
    dam: '2D6+4',
    tho: 1,
    range: '150',
    round: '全自动',
    num: '250',
    price: '3000/3万',
    err: '96',
    time: '1920s',
  },
  {
    name: '布伦轻机枪',
    skill: '射击(机枪)',
    dam: '2D6+4',
    tho: 1,
    range: '110',
    round: '1或全自动',
    num: '30/100',
    price: '3000/5万',
    err: '96',
    time: '1920s',
  },
  {
    name: '路易斯Ⅰ型机枪',
    skill: '射击(机枪)',
    dam: '2D6+4',
    tho: 1,
    range: '110',
    round: '全自动',
    num: '27/97',
    price: '3000/2万',
    err: '96',
    time: '1920s',
  },
  {
    name: 'GE M134式7.62mm速射机枪',
    skill: '射击(机枪)',
    dam: '2D6+4',
    tho: 1,
    range: '200',
    round: '全自动',
    num: '4000',
    price: '',
    err: '98',
    time: '现代',
  },
  {
    name: 'FN 米尼米，弹夹/弹带',
    skill: '射击(机枪)',
    dam: '2D6',
    tho: 1,
    range: '110',
    round: '全自动',
    num: '30/200',
    price: '',
    err: '99',
    time: '现代',
  },
  {
    name: '维克斯.303机枪',
    skill: '射击(机枪)',
    dam: '2D6+4',
    tho: 1,
    range: '110',
    round: '全自动',
    num: '250',
    price: '',
    err: '99',
    time: '1920s',
  },
  {
    name: '莫洛托夫鸡尾酒',
    skill: '投掷',
    dam: '2D6 烧',
    tho: 1,
    range: 'STRft',
    round: '1/2',
    num: '一次性',
    price: '',
    err: '95',
    time: '1920s，现代',
  },
  {
    name: '信号枪(信号弹枪)',
    skill: '射击(手枪)',
    dam: '1D10+1D3 烧',
    tho: 1,
    range: '10',
    round: '1/2',
    num: '1',
    price: '15/75',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: 'M79式40mm榴弹发射器',
    skill: '射击(重武器)',
    dam: '3D10/2码',
    tho: 1,
    range: '20',
    round: '1/3',
    num: '1',
    price: '',
    err: '99',
    time: '现代',
  },
  {
    name: '炸药棒',
    skill: '投掷',
    dam: '4D10/3码',
    tho: 1,
    range: 'STRft',
    round: '1/2',
    num: '一次性',
    price: '2/5',
    err: '99',
    time: '1920s，现代',
  },
  {
    name: '雷管',
    skill: '电气维修',
    dam: '2D10/1码',
    tho: 1,
    range: '',
    round: '',
    num: '一次性',
    price: '20/整盒',
    err: '100',
    time: '1920s，现代',
  },
  {
    name: '爆破筒',
    skill: '爆破',
    dam: '1D10/3码',
    tho: 1,
    range: '即地',
    round: '1',
    num: '一次性',
    price: '　',
    err: '95',
    time: '1920s，现代',
  },
  {
    name: '塑胶炸弹(C-4)，4盎司',
    skill: '爆破',
    dam: '6D10/3码',
    tho: 1,
    range: '即地',
    round: '1',
    num: '一次性',
    price: '',
    err: '99',
    time: '现代',
  },
  {
    name: '手榴弹',
    skill: '投掷',
    dam: '4D10/3码',
    tho: 1,
    range: 'STRft',
    round: '1/2',
    num: '一次性',
    price: '',
    err: '99',
    time: '1920s，现代',
  },
  {
    name: '81mm迫击炮',
    skill: '炮术',
    dam: '6D10/6码',
    tho: 1,
    range: '500',
    round: '1',
    num: '独立装弹',
    price: '',
    err: '100',
    time: '现代',
  },
  {
    name: '75mm野战火炮',
    skill: '炮术',
    dam: '10D10/2码',
    tho: 1,
    range: '500',
    round: '1/4',
    num: '独立装弹',
    price: '1500/-',
    err: '99',
    time: '1920s，现代',
  },
  {
    name: '120mm坦克主炮',
    skill: '炮术',
    dam: '10D10/2码',
    tho: 1,
    range: '2000',
    round: '1',
    num: '独立装弹',
    price: '',
    err: '100',
    time: '现代',
  },
  {
    name: '5英寸(127mm)舰炮',
    skill: '炮术',
    dam: '15D10/4码',
    tho: 1,
    range: '3000',
    round: '1',
    num: '自动上弹',
    price: '',
    err: '98',
    time: '1920s，现代',
  },
  {
    name: '反步兵地雷',
    skill: '爆破',
    dam: '4D10/5码',
    tho: 1,
    range: '即地',
    round: '1',
    num: '一次性',
    price: '',
    err: '99',
    time: '现代',
  },
  {
    name: '阔剑地雷',
    skill: '爆破',
    dam: '6D6/20码',
    tho: 1,
    range: '即地',
    round: '1',
    num: '一次性',
    price: '',
    err: '99',
    time: '现代',
  },
  {
    name: '火焰喷射器',
    skill: '射击(喷射器)',
    dam: '2D6+烧',
    tho: 1,
    range: '25',
    round: '1',
    num: '至少10',
    price: '',
    err: '93',
    time: '1920s，现代',
  },
  {
    name: 'M72式单发轻型反坦克炮',
    skill: '射击(重武器)',
    dam: '8D10/1码',
    tho: 1,
    range: '150',
    round: '1',
    num: '1',
    price: '',
    err: '98',
    time: '现代',
  },
];

export const weaponGroups: WeaponGroups = {
  // 常规
  cg: [
    '徒手格斗',
    '弓箭',
    '黄铜指虎',
    '长鞭',
    '燃烧的火把',
    '链锯',
    '包革金属棒(大头棍、护身棒)',
    '大棒(棒球棒、拨火棍)',
    '小型棍棒(警棍)',
    '弩',
    '绞索',
    '手斧/手镰',
    '大型刀(甘蔗刀等)',
    '中型刀(切肉餐刀等)',
    '小型刀(弹簧折叠刀等)',
    '220V通电导线',
    '催泪瓦斯',
    '双节棍',
    '投石',
    '手里剑',
    '矛、骑士长枪',
    '投矛',
    '大型剑(马刀)',
    '中型剑(佩剑、重剑)',
    '轻型剑(花剑、剑杖)',
    '电击枪(接触)',
    '电击枪(射击)',
    '战斗回力镖',
    '伐木斧',
  ],
  // 手枪
  sq: [
    '燧发手枪',
    '.22(5.6mm)小型自动手枪',
    '.25(6.35mm)短口手枪(单管)',
    '.32(7.65mm)左轮',
    '.32(7.65mm)自动手枪',
    '.357马格南左轮',
    '.38(9mm)左轮',
    '.38(9mm)自动手枪',
    '贝瑞塔M9',
    '9mm格洛克17',
    '9mm鲁格P08',
    '.41(10.4mm)左轮',
    '.44(11.2mm)马格南左轮',
    '.45(11.43mm)左轮',
    '.45(11.43mm)自动手枪',
    'IMI 沙漠之鹰',
  ],
  // 半自动步枪
  bbq: [
    '.58 (14.7mm)1855年式春田步枪',
    '.22 (5.6mm)栓式枪机步枪',
    '.30 (7.62mm)杠杆式枪机步枪',
    '.45 (11.43mm)马蒂尼-亨利步枪',
    '莫兰上校的气动步枪③',
    '加兰德M1、M2步枪',
    'SKS半自动步枪(56半)',
    '.303(7.7mm)李-恩菲尔德',
    '.30-06(7.62mm)手动枪机步枪',
    '.30-06(7.62mm)半自动步枪',
    '.444(11.28mm)马林步枪',
    '猎象枪(双管)',
  ],
  // 全自动步枪
  tsq: [
    'AK-47或AKM',
    'AK-74',
    'FN FAL 突击步枪',
    '加利尔突击步枪',
    'M16A2',
    'M4',
    '斯泰尔AUG',
    '贝雷塔AR70/90',
  ],
  // 霰弹枪
  xdq: [
    '20号霰弹枪(双管)',
    '16号霰弹枪(双管)',
    '12号霰弹枪(双管)',
    '12号霰弹枪(手压式)',
    '12号霰弹枪(半自动)',
    '12号霰弹枪(双管,锯短)',
    '10号霰弹枪(双管)',
    '12号贝里尼M3(折叠式枪托)',
    '12号SPAS (折叠式枪托)',
  ],
  // 冲锋枪
  cfq: ['MP18I/M现代28II', 'MP5', 'MAC-11', '蝎式', '汤普森', '乌兹'],
  // 狙击步枪
  jjbq: ['巴雷特M82', 'PTRD-41反坦克步枪'],
  // 机枪
  jq: [
    '1882年式加特林',
    'M1918式勃朗宁自动步枪',
    '勃朗宁M1917A1(7.62mm)',
    '布伦轻机枪',
    '路易斯Ⅰ型机枪',
    'GE M134式7.62mm速射机枪',
    'FN 米尼米，弹夹/弹带',
    '维克斯.303机枪',
  ],
  // 其它
  qt: [
    '莫洛托夫鸡尾酒',
    '信号枪(信号弹枪)',
    'M79式40mm榴弹发射器',
    '炸药棒',
    '雷管',
    '爆破筒',
    '塑胶炸弹(C-4)，4盎司',
    '手榴弹',
    '81mm迫击炮',
    '75mm野战火炮',
    '120mm坦克主炮',
    '5英寸(127mm)舰炮',
    '反步兵地雷',
    '阔剑地雷',
    '火焰喷射器',
    'M72式单发轻型反坦克炮',
  ],
};

export const weaponGroupOrders: [keyof WeaponGroups, string][] = [
  ['cg', '常规'],
  ['sq', '手枪'],
  ['bbq', '半自动步枪'],
  ['tsq', '全自动步枪'],
  ['xdq', '霰弹枪'],
  ['cfq', '冲锋枪'],
  ['jjbq', '狙击步枪'],
  ['jq', '机枪'],
  ['qt', '其它'],
];
